/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Color;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.IOException;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JPanel;

/**
 *
 * @author xp
 */
public class VentanaPokedex extends javax.swing.JFrame {

    BufferedImage buffer = null;
    Image imagen1 = null;
    int slide = 0;

    //variables que conectan mySQL con java
    Statement estado;
    ResultSet resultadoConculta;
    Connection conexion;
    Clip boton=null;

    @Override
    public void paint(Graphics g) {
        super.paintComponents(g);
        Graphics2D g2 = (Graphics2D) imagenPokemon.getGraphics();
        g2.drawImage(buffer, 0, 0, imagenPokemon.getWidth(),
                imagenPokemon.getHeight(), null);
    }

    /**
     * Creates new form VentanaPokedex
     */
    public VentanaPokedex() {
        
        initComponents();
        setSize(950, 750);
        try {
            imagen1 = ImageIO.read(getClass().getResource("/imagenes/black-white.png"));
        } catch (IOException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
        }
        //asi hacemos que se dibujen pokemones en jpanel
        buffer = (BufferedImage) imagenPokemon.createImage(imagenPokemon.getWidth(),
                imagenPokemon.getHeight());

        Graphics2D g2 = buffer.createGraphics();
        dibujaElPokemonQueEstaEnLaPOsicion(slide);
        //conectamos la mysql con jaba
        try {
            Class.forName("com.mysql.jdbc.Driver");
            conexion = DriverManager.getConnection("jdbc:mysql://192.168.182.140/pokemon", "root", "");
            estado = conexion.createStatement();
        } catch (Exception e) {
            System.out.println(e.getMessage());
            System.out.println("Paso por catch");

        }

    }
    private void boton() {
        try {
            boton = AudioSystem.getClip();
            boton.open(AudioSystem.getAudioInputStream(getClass().getResource("/Sonido/button-3.wav")));
        } catch (Exception ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("sonido ha petado");
            
        }
        boton.start();
    }

    private void dibujaElPokemonQueEstaEnLaPOsicion(int posicion) {
        int fila = posicion / 31;
        int columna = posicion % 31;
        Graphics2D g2 = (Graphics2D) buffer.createGraphics();
        g2.setColor(Color.black);
        //pinta el fondo de jpanel de negro 
        g2.fillRect(0, 0, imagenPokemon.getWidth(), imagenPokemon.getHeight());
        g2.drawImage(imagen1, 0, 0, imagenPokemon.getWidth(),
                imagenPokemon.getHeight(),
                columna * 96,
                fila * 96,
                columna * 96 + 96,
                fila * 96 + 96, null);
        repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NombrePokemon = new javax.swing.JLabel();
        Descripcion = new javax.swing.JTextArea();
        imagenPokemon = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        Habitat = new javax.swing.JLabel();
        Especie = new javax.swing.JLabel();
        Tipo1 = new javax.swing.JLabel();
        Movimiento1 = new javax.swing.JLabel();
        Movimiento2 = new javax.swing.JLabel();
        Peso = new javax.swing.JLabel();
        Altura = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 0, 51));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        getContentPane().setLayout(null);

        NombrePokemon.setBackground(new java.awt.Color(0, 0, 0));
        NombrePokemon.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        NombrePokemon.setForeground(new java.awt.Color(51, 51, 255));
        getContentPane().add(NombrePokemon);
        NombrePokemon.setBounds(270, 460, 140, 30);

        Descripcion.setColumns(20);
        Descripcion.setRows(5);
        getContentPane().add(Descripcion);
        Descripcion.setBounds(270, 390, 300, 70);

        javax.swing.GroupLayout imagenPokemonLayout = new javax.swing.GroupLayout(imagenPokemon);
        imagenPokemon.setLayout(imagenPokemonLayout);
        imagenPokemonLayout.setHorizontalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 320, Short.MAX_VALUE)
        );
        imagenPokemonLayout.setVerticalGroup(
            imagenPokemonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 260, Short.MAX_VALUE)
        );

        getContentPane().add(imagenPokemon);
        imagenPokemon.setBounds(260, 40, 320, 260);

        jButton2.setBorderPainted(false);
        jButton2.setContentAreaFilled(false);
        jButton2.setOpaque(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(191, 480, 40, 30);

        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.setOpaque(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(120, 480, 40, 30);

        Habitat.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(Habitat);
        Habitat.setBounds(420, 550, 150, 30);

        Especie.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(Especie);
        Especie.setBounds(270, 580, 300, 30);

        Tipo1.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(Tipo1);
        Tipo1.setBounds(270, 550, 160, 32);

        Movimiento1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Movimiento1);
        Movimiento1.setBounds(270, 490, 300, 30);

        Movimiento2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(Movimiento2);
        Movimiento2.setBounds(350, 520, 220, 30);

        Peso.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(Peso);
        Peso.setBounds(420, 460, 70, 30);

        Altura.setFont(new java.awt.Font("Comic Sans MS", 0, 14)); // NOI18N
        getContentPane().add(Altura);
        Altura.setBounds(490, 460, 80, 30);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/pokedex_consola.png"))); // NOI18N
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 0, 1219, 660);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (slide < 152) {
            slide++;
        }
        dibujaElPokemonQueEstaEnLaPOsicion(slide);
        try {
            resultadoConculta = estado.executeQuery("select * from pokemon where id=" + (slide + 1));
            if (resultadoConculta.next()) {
                NombrePokemon.setText("Nombre:" + resultadoConculta.getString(2));
                Descripcion.setLineWrap(true);
                Descripcion.setText(resultadoConculta.getString(16));
                Altura.setText("Altura: " + resultadoConculta.getString(3));
                Peso.setText("Peso: " + resultadoConculta.getString(4));
                Habitat.setText("Habitat: " + resultadoConculta.getString(6));
                Especie.setText("Especie: " + resultadoConculta.getString(5));
                Tipo1.setText("Tipos: " + resultadoConculta.getString(7) + ", " + resultadoConculta.getString(8));
                Movimiento1.setText("Movimientos: " + resultadoConculta.getString(10) + ", " + resultadoConculta.getString(11));
                Movimiento2.setText(resultadoConculta.getString(12) + ", " + resultadoConculta.getString(13));
            } else {
                 NombrePokemon.setText("...");
                Descripcion.setText("...");
                Altura.setText("...");
                Peso.setText("...");
                Habitat.setText("...");
                Especie.setText("...");
                Tipo1.setText("..." + ", " + "...");
                Movimiento1.setText("..."  + ", " + "...");
                Movimiento2.setText("..."+ ", " + "...");
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("ha petado la consulta");
        }
        boton();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (slide > 0) {
            slide--;
        }
        dibujaElPokemonQueEstaEnLaPOsicion(slide);

        try {
            resultadoConculta = estado.executeQuery("select * from pokemon where id=" + (slide + 1));
            if (resultadoConculta.next()) {
                NombrePokemon.setText("Nombre:" + resultadoConculta.getString(2));
                Descripcion.setLineWrap(true);
                Descripcion.setText(resultadoConculta.getString(16));
                Altura.setText("Altura: " + resultadoConculta.getString(3));
                Peso.setText("Peso: " + resultadoConculta.getString(4));
                Habitat.setText("Habitat: " + resultadoConculta.getString(6));
                Especie.setText("Especie: " + resultadoConculta.getString(5));
                Tipo1.setText("Tipos: " + resultadoConculta.getString(7) + ", " + resultadoConculta.getString(8));
                Movimiento1.setText("Movimientos: " + resultadoConculta.getString(10) + ", " + resultadoConculta.getString(11));
                Movimiento2.setText(resultadoConculta.getString(12) + ", " + resultadoConculta.getString(13));
            } else {
                NombrePokemon.setText("...");
                Descripcion.setText("...");
                Altura.setText("...");
                Peso.setText("...");
                Habitat.setText("...");
                Especie.setText("...");
                Tipo1.setText("..." + ", " + "...");
                Movimiento1.setText("..."  + ", " + "...");
                Movimiento2.setText("..."+ ", " + "...");
                
            }
        } catch (SQLException ex) {
            Logger.getLogger(VentanaPokedex.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("ha petado la consulta");
        }
        boton();

    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPokedex.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPokedex().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Altura;
    private javax.swing.JTextArea Descripcion;
    private javax.swing.JLabel Especie;
    private javax.swing.JLabel Habitat;
    private javax.swing.JLabel Movimiento1;
    private javax.swing.JLabel Movimiento2;
    private javax.swing.JLabel NombrePokemon;
    private javax.swing.JLabel Peso;
    private javax.swing.JLabel Tipo1;
    private javax.swing.JPanel imagenPokemon;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel7;
    // End of variables declaration//GEN-END:variables
}
